# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
env:
  ARG: my-arg
jobs:
  db:
    name: Run db command
    uses: ./.github/workflows/exec-command.yml
    with:
      command: ls ${{ env.ARG }}
      
      
