# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
env:
  ARG: my-arg
  
jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - id: step1
        name: Define command
        run: echo "command=${{env.ARG}}" >> "$GITHUB_OUTPUT"
    outputs:
      command: ${{ steps.step1.outputs.command }}
        
  db:
    name: Run db command
    needs: init
    uses: ./.github/workflows/exec-command.yml
    with:
      command: ls ${{ needs.init.outputs.command }}
      
      
