# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  init:
    name: Init
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "ARG=my-arg" >> $GITHUB_ENV
  db:
    name: Run db command
    uses: ./.github/workflows/exec-command.yml
    with:
      command: ls $ARG
      
      
