# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:


jobs:
  echo:
    name: "Echo test"
    
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "test"

  trigger_next:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Next Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: start-next-workflow
          client-payload: '{"input1": "value1", "input2": "value2"}'
    
