# This is a basic workflow to help you get started with Actions

name: First Workflow

# Controls when the workflow will run
on:
  workflow_dispatch:


jobs:
  echo:
    name: "Echo test"
    
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "test"
    
