# This is a basic workflow to help you get started with Actions

name: Second Workflow

# Controls when the workflow will run
on:
  push:
    branches:
      - devel-1
      
  workflow_dispatch:

  workflow_run:
    workflows: ["First Workflow"]
    types: [complete]

jobs:
  echo:
    name: "Second echo"
    
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "test"
