# This is a basic workflow to help you get started with Actions

name: Second Workflow

# Controls when the workflow will run
on:
  repository_dispatch:
    types: [start-next-workflow]

jobs:
  echo:
    name: "Second echo"
    
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "Input 1: ${{ github.event.client_payload.input1 }}"
          echo "Input 2: ${{ github.event.client_payload.input2 }}"
